name: Deploy GitHub Pages
description: Deploy your site to GitHub
inputs:
  github_token:
    description: User's GITHUB_TOKEN
    required: true
  build_dir:
    description: Output JS directory
    required: false
    default: dist
  target_dir:
    description: Directory to serve from
    required: false
    default: docs

runs:
  using: composite
  steps:
    - run: ${{ github.action_path}}/action.sh
      shell: bash
      env:
        BUILD_DIR: ${{ inputs.build_dir }}
        TARGET_DIR: ${{ inputs.target_dir }}
  # args:
  #   - ${{ inputs.github_token }}
  #   - ${{ inputs.build_dir }}
  #   - ${{ inputs.target_dir }}
