name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_dir: my-app
          build_dir: my-app/build
